### ISSUE TITLE
maennchen/ZipStream-PHP v3

### ISSUE THREAD

**Issue by MannikJ** [stechstudio/laravel-zipstream#107]
Are there any plans for the near future to upgrade this package to maennchen/ZipStream-PHP v3?

**Comment by jszobody** [comment]
Yes. It's just a major rewrite, and I haven't been able to prioritize that just yet. Hopefully soon.

**Comment by ilvalerione** [comment]
+1

**Comment by mbardelmeijer** [comment]
@jszobody do you have a global outline in terms of planning for when the package supports ZipStream V3? 😄 Just planning our application upgrade.

**Comment by jszobody** [comment]
Is that holding back your application upgrade? We have Laravel 11 apps using this package currently without issue. I'm aware of some conflicts with other packages like Spatie's medialibrary, but there should be no obstacle to upgrading Laravel itself.

Otherwise, I hope to work on this in May. This month isn't going to happen.

**Comment by mbardelmeijer** [comment]
@jszobody it's indeed due to a conflict with the latest `spatie/laravel-medialibrary` package, in combination with `spatie/laravel-medialibrary-pro`

Thanks for the update there! And thanks for maintaining this package 🙏

**Comment by jszobody** [comment]
@mbardelmeijer If you are zipping files that are handled by spatie/medialibrary, are you aware that medialibrary can fully handle the zip stream? You might not need this package at all.

https://spatie.be/docs/laravel-medialibrary/v11/downloading-media/downloading-multiple-files

(Apologies if I'm telling you something obvious!)

**Comment by jszobody** [comment]
@mbardelmeijer Yep, got it. Makes sense.

**Comment by aerni** [comment]
Any update on this issue? This is currently holding back the update of my Statamic sites, as Statamic 5 now requires `"maennchen/zipstream-php": "^3.1"`. Thanks for your work on this wonderful package!

**Comment by padre** [comment]
Hello everyone! does anyone know if this problem is going to be fixed? Thanks!

**Comment by jszobody** [comment]
Hey everyone. Version `5.0-beta` was tagged this morning. 

https://github.com/stechstudio/laravel-zipstream/releases/tag/5.0-beta

This is a pretty major refactor based on `maennchen/ZipStream-PHP` 3.1. I would appreciate any helping testing this!

**Comment by mbardelmeijer** [comment]
> Hey everyone. Version `5.0-beta` was tagged this morning.
> 
> [`5.0-beta` (release)](https://github.com/stechstudio/laravel-zipstream/releases/tag/5.0-beta)
> 
> This is a pretty major refactor based on `maennchen/ZipStream-PHP` 3.1. I would appreciate any helping testing this!

Works perfectly with our use case (i.e. zipping files using the `STS\ZipStream\Models\S3File` model) 💪  -- Thanks!

**Comment by aerni** [comment]
Works as expected!

**Comment by padre** [comment]
> Hey everyone. Version `5.0-beta` was tagged this morning.
> 
> https://github.com/stechstudio/laravel-zipstream/releases/tag/5.0-beta
> 
> This is a pretty major refactor based on `maennchen/ZipStream-PHP` 3.1. I would appreciate any helping testing this!

@jszobody Works perfectly. Thanks!

**Comment by jszobody** [comment]
Ok v5 was just released as stable. Thanks everyone!

One additional change that was added since the beta: `flushOutput` is set to true in the underlying package to reduce buffering. In our testing this _dramatically_ improves the initial zip start time and memory usage. In a test of about 1k files from S3, it was taking 7-10s before the zip response was first received in the browser. With the flush option turned on, this dropped to ~300ms. Memory usage during the zipping process was barely detectable, compared with relatively high memory usage before.
