### ISSUE TITLE
filesize() error for comment in file

### ISSUE THREAD

**Issue by postwirt** [stechstudio/laravel-zipstream#12]
If a comment is written at the very beginning of a file (tried for a css and a js file), then you run into an filesize() error by trying to zip it. The comment is written like `/*Comment*/`

**Comment by jszobody** [comment]
It sounds like you're adding the raw file contents directly to the Zip, is that correct?

If so, use the `->addRaw($content, $filename)` method instead of the catch-all `->add(...)` method. The `add` method tries to guess what you are adding, and that initial slash makes it look like a path on disk.

**Comment by postwirt** [comment]
yes, that is correct. 

I tried and it is working. So it was my fault. 
Thanks for the answer.
