### ISSUE TITLE
error buildArchiveOptions() must be of the type array

### ISSUE THREAD

**Issue by normeno** [stechstudio/laravel-zipstream#24]
Hi,

I was doing the same simple test via tinker on 2 different machines, and I get different results.

![image](https://user-images.githubusercontent.com/6278347/89439002-8ee7d880-d717-11ea-8dd3-f89884549545.png)

![image](https://user-images.githubusercontent.com/6278347/89439026-97401380-d717-11ea-88f0-a2670e13242f.png)

What is going wrong?

The version of Laravel is the same, the only difference I see is that in the test that does not fail, the version of php is 7.2.10, and the one that fails is 7.2.24

**Comment by jszobody** [comment]
Hmm so the `buildArchiveOptions()` is getting `null` instead of an array. 

When the service provider [calls this method](https://github.com/stechstudio/laravel-zipstream/blob/659e04ec40cfa2e0ca07383d84f172b3b144989a/src/ZipStreamServiceProvider.php#L40) it is passing in `$app['config']->get('zipstream.archive')`.

If you [look at the config file](https://github.com/stechstudio/laravel-zipstream/blob/master/config/config.php#L8-L10) that is an array.

Have you published the config file locally and modified it perhaps?

Worth trying `config('zipstream.archive')` in your tinker session and seeing what you have there, it needs to be an array.

**Comment by normeno** [comment]
It is correct, in one project it returns an array, in another it returns null.

![image](https://user-images.githubusercontent.com/6278347/89440084-239f0600-d719-11ea-9522-f7a4c1dca2d1.png)

![image](https://user-images.githubusercontent.com/6278347/89440106-2b5eaa80-d719-11ea-8b78-a3404d127ef7.png)

The strange thing is that it is the same project, so the settings are the same

**Comment by jszobody** [comment]
Maybe try `php artisan config:clear`? 

Not sure what to tell you if that doesn't fix it. You're definitely dealing with an issue of config not being loaded, which is outside the scope of this specific package. Once you figure out the config issue, you should be good to go.
