### ISSUE TITLE
How To Dynamically Build ZIP

### ISSUE THREAD

**Issue by aerni** [stechstudio/laravel-zipstream#30]
How would you go about adding files dynamically to the zip? I have an array of file paths in my view. I want to give the user the option to download a zip instead of each file separately. I'm thinking about an anchor tag that links to the zip. But somehow I have to create that zip with the assets present in the view.

The only solution I can come up with is a GET request with the asset paths as parameters. The GET request then triggers the build of the zip and returns the stream. Does this make sense? Any other way I don't see?

Thanks a lot for you great work!

**Comment by jszobody** [comment]
Sure, of course you can add files dynamically. Almost all the zips I build are dynamic. Super simple example:

```php
$filepaths = ["/path/to/file1.txt", "path/to/file2/pdf"];
$zip = Zip::create("package.zip");

foreach($filepaths AS $filepath) {
    $zip->add($filepath);
}

return $zip;
```

While those filepaths _could_ come from request parameters, for security reasons you _never_ want to let your user pass in filepaths, since a malicious user could trick your app into zipping up sensitive files from your server. 

In my apps, any file has some kind of database ID. So the GET parameters are file IDs, and then I fetch the filepaths from the database when building the zip, without letting the user ever see or specify those.

**Comment by aerni** [comment]
Thanks for taking the time to answer this. Makes total sense. I'm going to implement this like you're suggesting.
