### ISSUE TITLE
get_headers(): php_network_getaddresses: getaddrinfo failed: Name or service not known

### ISSUE THREAD

**Issue by kamran-ashlarglobal** [stechstudio/laravel-zipstream#43]
i have more than 500 images uploaded on s3 bucket but when i create zip from s3 urls then flow breaks and i got the error. sometimes its working and most of the times its not working. Please help me if you can resolve this error.

**Comment by jszobody** [comment]
Are you adding these with `https://` urls, or `s3://` paths? I strong recommend the latter, so that this package will use the AWS S3Client to create the file streams.

**Comment by kamran-ashlarglobal** [comment]
yes i am adding with https://

**Comment by kamran-ashlarglobal** [comment]
sometimes its work and most of the times not work.

**Comment by jszobody** [comment]
Usually `php_network_getaddresses: getaddrinfo failed` means php can't find the hostname. You're hitting that when the package tries to simply call [`get_headers`](https://www.php.net/get_headers) on your URL. I believe that is something outside the scope of this package, I can't help you with that.

My advice would be to switch to `s3://` so that this package can use the AWS SDK instead of working with a plain URL source. I believe that will solve your issue if you get that all set up.
