### ISSUE TITLE
Error executing "PutObject"  EntityTooLarge

### ISSUE THREAD

**Issue by subtainishfaq7175** [stechstudio/laravel-zipstream#46]
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>EntityTooLarge</Code><Message>Your proposed upload exceeds the maxim (truncated...)
EntityTooLarge (client): Your proposed upload exceeds the maximum allowed size - <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>EntityTooLarge</Code><Message>Your proposed upload exceeds the maximum allowed size</Message><ProposedSize>7437099286</ProposedSize><MaxSizeAllowed>5368709120</MaxSizeAllowed>

We have Zips larger than 5GB and is there a way to use uploader rather than putObject, we are calling saveTo function

**Comment by jszobody** [comment]
There is no support for that currently. I haven't been able to look into how we might implement that. Once challenge is that the Uploader seems to assume the source file is fully present and ready to upload, and uses a blocking call to perform the upload. This package has to _write_ out at the same time it is _building_ the zip data.

If you decide to work on it and come up with a solution, feel free to post a PR for review. Otherwise at the moment you might just consider saving the file locally and then using Uploader.
