### ISSUE TITLE
Unexpected end of Archive

### ISSUE THREAD

**Issue by mecjos** [stechstudio/laravel-zipstream#85]
Hi.. 

I try to download several parts via following code.. 

```
$order = Order::find($id);
        $zipFile = Zip::create('CadFiles_'.$order->order_no . '.zip');
        foreach ($order->jobs as $job) {
            foreach ($job->part->cads as $cad) {
                $zipFile->addRaw(Storage::disk($cad->disk)->get($cad->path), $cad->name);
            }
        }
        return $zipFile;
```
after download zip file I get unexpected end of archive error...  Where am I wrong?

**Comment by jszobody** [comment]
Hi there, I can't reproduce your issue with `addRaw`. I tried this simple test:

```php
Zip::create('download.zip')
            ->addRaw("some file contents", "text1.txt")
            ->addRaw("more dummy file contents", "text2.txt");
```

... and I got a valid `download.zip` file with two files inside.

Also, I would recommend that you provide the _path_ to your files with `->add()`, rather than fetching the entire file contents yourself and using `->addRaw`. When you provide the path, this package will open a file handle and stream in the file contents, which is much better for memory management. 

If you continue to have issues with adding files, please provide a reproducible test case that I can look at.
