### ISSUE TITLE
Filename sanitization

### ISSUE THREAD

**Issue by kw-pr** [stechstudio/laravel-zipstream#94]
I noticed you do [filename sanitization](https://github.com/stechstudio/laravel-zipstream#filename-sanitization) and the option to turned it of `ZIPSTREAM_FILE_SANITIZE=false`.

I was wondering why you do this sanitization and what implication does it have if we turn it off.

I turned if off to allow chinese characters and for the moment it worked fine but maybe I need to add a custom sanitization for other cases?

**Comment by jszobody** [comment]
I often generate zips from dynamic user-provided input, like projects names. I've personally had a lot of issues where zips break because of a character that isn't allowed in a Windows filepath, or even strange zerowidth unicode characters, stuff like that. I decided I wanted to just convert everything to ascii to eliminate any issues with invalid characters.

You can absolutely turn off the ascii sanitization, it's definitely a sledgehammer approach that wouldn't work if you want to allow other character sets. Just consider what you're allowing through in your zip file name, and zip paths.

**Comment by kw-pr** [comment]
Thanks I finally disabled your escaping and added my own:

```php
$filename = preg_replace('/[^[:alnum:] ._~-]+/u', '_', $filename);
```

I checked this with the 44k filenames I have in my database.
